### ISSUE TITLE
sql导入失败了

### ISSUE THREAD

**Issue by Flying-Cabbage** [looniink/hotelManage#1]
你好·sql导入失败了
![image](https://user-images.githubusercontent.com/54514945/215451364-53798405-528b-498e-a087-a4cb521c47ae.png)
无论是8版本mysql还是5版本mysql全部失败

**Comment by looniink** [comment]
抱歉才看见，用5.6版本的MySQL就好了

**Comment by Xiaolu-996** [comment]
> 你好·sql导入失败了 ![image](https://user-images.githubusercontent.com/54514945/215451364-53798405-528b-498e-a087-a4cb521c47ae.png) 无论是8版本mysql还是5版本mysql全部失败

抱歉才看见，用5.6版本的MySQL就好了
